[package]
name = "mce-cli"
version = "0.1.0"
description = "CLI tool for MCE"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mce-core.workspace = true
mce-fst.workspace = true
mce-tokenizer.workspace = true
mce-speller.workspace = true
mce-disambig.workspace = true
mce-comonad.workspace = true
mce-fi.workspace = true
mce-grammar.workspace = true
