[package]
name = "mce-wasm"
version = "0.1.0"
description = "WASM bindings for MCE"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mce-core.workspace = true
mce-fst.workspace = true
mce-fi.workspace = true
mce-speller.workspace = true
mce-disambig.workspace = true
mce-comonad.workspace = true
mce-tokenizer.workspace = true
mce-grammar.workspace = true
wasm-bindgen.workspace = true
js-sys.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = true
