[package]
name = "mce-core"
version.workspace = true
description = "Shared types and data structures for MCE"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "trie_bench"
harness = false
